import json
import unittest
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def read_text(path): return (ROOT / path).read_text(encoding="utf-8")
class ProjectContractTests(unittest.TestCase):
    def test_identity_and_minimal_permissions(self):
        manifest = json.loads(read_text("manifest.json.in"))
        cmake = read_text("CMakeLists.txt")
        self.assertEqual(manifest["name"], "nexttasks.cloudsite")
        self.assertEqual(manifest["title"], "NextTasks")
        self.assertIn('set(NEXTTASKS_VERSION "0.1.0")', cmake)
        self.assertEqual(manifest["version"], "@NEXTTASKS_VERSION@")
        self.assertEqual(manifest["architecture"], "$ENV{ARCH}")
        self.assertEqual(manifest["framework"], "$ENV{CLICK_FRAMEWORK}")
        self.assertIn("nexttasks", manifest["hooks"])
        self.assertEqual(manifest["hooks"]["nexttasks"]["content-hub"], "nexttasks-contenthub.json")
        apparmor = read_text("nexttasks.apparmor")
        self.assertIn('"accounts"', apparmor)
        self.assertIn('"networking"', apparmor)
        self.assertIn('"content_exchange"', apparmor)
        self.assertIn('"content_exchange_source"', apparmor)
        self.assertNotIn("unconfined", apparmor)
        self.assertNotIn("template", apparmor)
        content_hub = json.loads(read_text("nexttasks-contenthub.json"))
        self.assertEqual(content_hub, {
            "destination": ["text", "links", "documents"],
            "share": ["text", "links", "documents"],
            "source": ["text", "links", "documents"]
        })
    def test_online_accounts_providers_are_declared(self):
        accounts = read_text("nexttasks.accounts")
        self.assertIn('"provider": "nextcloud"', accounts)
        self.assertIn('"provider": "owncloud"', accounts)
        self.assertIn("Use this Nextcloud account for NextTasks.", accounts)
    def test_runtime_files_and_docs_exist(self):
        for path in ["qml/Main.qml", "qml/pages/HomePage.qml", "qml/pages/TaskDetailPage.qml", "qml/pages/TaskConflictResolutionPage.qml", "qml/pages/AccountSelectionPage.qml", "qml/pages/SettingsPage.qml", "qml/pages/LanguageSelectionPage.qml", "qml/pages/AboutPage.qml", "qml/backend/AuthCore.js", "qml/backend/AccountSessionAdapter.qml", "qml/backend/TasksApiClient.qml", "qml/backend/TasksController.qml", "qml/backend/TasksCache.qml", "scripts/desktop-test.sh", "assets/logo.svg", "assets/openstore-banner.svg", "README.md", "CHANGELOG.md", "LICENSE"]:
            self.assertTrue((ROOT / path).exists(), path)
        self.assertIn("nexttasksAppVersion", read_text("qml/pages/AboutPage.qml"))
        self.assertIn('Version %1', read_text("qml/pages/AboutPage.qml"))
    def test_online_accounts_flow_contract(self):
        account_page = read_text("qml/pages/AccountSelectionPage.qml")
        qrc = read_text("qml/qml.qrc")
        self.assertIn('appApplicationId: "nexttasks.cloudsite_nexttasks"', account_page)
        self.assertIn('nextcloudServiceId: "nexttasks.cloudsite_nexttasks_nextcloud"', account_page)
        self.assertIn('owncloudServiceId: "nexttasks.cloudsite_nexttasks_owncloud"', account_page)
        self.assertIn("service-not-enabled", account_page)
        self.assertIn("Open Ubuntu Touch System Settings > Accounts", account_page)
        self.assertIn("openSystemAccountsDialog", account_page)
        self.assertIn('Qt.openUrlExternally("settings://system/online-accounts")', account_page)
        self.assertIn("function systemAccountsDialogText()", account_page)
        self.assertIn("function retryAfterSystemApproval()", account_page)
        self.assertIn("waitingForSystemApproval", account_page)
        self.assertIn("lowerMessage.indexOf(\"apparmor policy prevents\")", account_page)
        self.assertIn("PopupUtils.open(openSystemAccountsDialog)", account_page)
        self.assertIn("selectedHasServiceHandle", account_page)
        self.assertIn("if (!selectedEnabled && !selectedHasServiceHandle)", account_page)
        self.assertIn("if (selectedEnabled || selectedHasServiceHandle)", account_page)
        self.assertIn("select %1", account_page)
        self.assertIn("verify it automatically", account_page)
        self.assertNotIn("select it again", account_page)
        self.assertIn('i18n.tr("Open system accounts")', account_page)
        self.assertIn("function clearSelectedAccount()", account_page)
        self.assertIn("clearSelectedAccount()", account_page)
        self.assertIn("function restoreSelectedAccountFromSettings()", account_page)
        self.assertIn("accountSettings.accountId === row.role(\"accountId\")", account_page)
        self.assertIn("accountSettings.serviceId === rowServiceId", account_page)
        self.assertIn("authorizationRunning", account_page)
        self.assertIn("if (page.authorizationRunning)", account_page)
        self.assertIn("page.selectAccount(", account_page)
        self.assertNotIn("Discovered services:", account_page)
        self.assertNotIn("Diagnostics", account_page)
        self.assertNotIn('text: row.isSelected ? i18n.tr("Selected") : i18n.tr("Use")', account_page)
        self.assertNotIn('selectedService.updateServiceEnabled(true)', account_page)
        self.assertIn('page.commitServerUrlInput("authenticate")', account_page)
        self.assertIn("<file>backend/AuthCore.js</file>", qrc)
        self.assertIn("<file>backend/AccountSessionAdapter.qml</file>", qrc)

    def test_content_hub_text_import_export_contract(self):
        cmake = read_text("CMakeLists.txt")
        main = read_text("main.cpp")
        qrc = read_text("qml/qml.qrc")
        home = read_text("qml/pages/HomePage.qml")
        detail = read_text("qml/pages/TaskDetailPage.qml")
        controller = read_text("qml/backend/TasksController.qml")
        import_handler = read_text("qml/backend/TaskShareImportHandler.qml")
        export_page = read_text("qml/backend/TaskShareExportPage.qml")
        bridge = read_text("ContentHubBridge.cpp")

        self.assertIn("install(FILES ${PROJECT_NAME}-contenthub.json", cmake)
        self.assertIn("ContentHubBridge.cpp", cmake)
        self.assertIn("setContextProperty(QStringLiteral(\"contentHubBridge\")", main)
        for qml_file in [
            "TaskShareImportHandler.qml",
            "TaskShareImportHandlerUbuntu.qml",
            "TaskShareExportPage.qml",
            "TaskShareExportPageUbuntu.qml",
        ]:
            self.assertIn(qml_file, qrc)

        self.assertIn("TaskShareImportHandler.qml", home)
        self.assertIn("handleSharedTextReceived", home)
        self.assertIn("shareImportListDialog", home)
        self.assertIn("createTaskFromSharedText", home)
        self.assertIn("Select where the shared text task should be created.", home)
        self.assertIn("function createTaskFromSharedText", controller)
        self.assertIn("function titleFromSharedText", controller)
        self.assertIn("function sharedDateTaskTitle()", controller)
        self.assertIn("function descriptionFromSharedText", controller)
        self.assertIn("titleText.slice(0, 80)", controller)
        self.assertIn("text.slice(80).trim()", controller)
        self.assertIn('var months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"', controller)

        self.assertIn("ContentHub.hasPending", import_handler)
        self.assertIn("ContentHub.restoreImports()", import_handler)
        self.assertIn("ContentHub.finishedImports", import_handler)
        self.assertIn("ContentTransfer.Collected", import_handler)
        self.assertIn("contentHubBridge.readTextFile", import_handler)
        self.assertNotIn("console.log(content", import_handler)

        self.assertIn("function shareCurrentTask()", detail)
        self.assertIn("TaskShareExportPage.qml", detail)
        self.assertIn("TaskShareExportPageUbuntu.qml", detail)
        self.assertIn("ContentHandler.Share", export_page)
        self.assertIn("item.text = shareText", export_page)
        self.assertIn("writeSharedTextFile", bridge)
    def test_settings_contract(self):
        settings = read_text("qml/pages/SettingsPage.qml")
        language = read_text("qml/pages/LanguageSelectionPage.qml")
        self.assertIn('property string swipeActionLayout: "ut"', settings)
        self.assertIn('i18n.tr("Swipe actions")', settings)
        self.assertIn('i18n.tr("Ubuntu Touch style")', settings)
        self.assertIn('i18n.tr("Upstream-compatible style")', settings)
        self.assertIn('appSettings.swipeActionLayout = modelData.value', settings)
        self.assertIn("id: languageList", language)
        self.assertIn("width: languageList.width", language)
        self.assertIn("spacing: units.gu(0.1)", language)
        for locale in ["", "en", "sv", "da", "de", "es", "fi", "fr", "it", "nb", "nl", "pl", "ru", "uk"]:
            self.assertIn('"code": "%s"' % locale, language)
        for po_file in ["da.po", "de.po", "es.po", "fi.po", "fr.po", "it.po", "nb.po", "nl.po", "pl.po", "ru.po", "uk.po"]:
            self.assertTrue((ROOT / "po" / po_file).exists(), po_file)
            self.assertIn("AI-assisted starter translation", read_text("po/" + po_file))
    def test_desktop_test_and_api_contract(self):
        main = read_text("main.cpp")
        script = read_text("scripts/desktop-test.sh")
        api = read_text("qml/backend/TasksApiClient.qml")
        caldav_network = read_text("CalDavNetwork.cpp")
        cmake = read_text("CMakeLists.txt")
        qrc = read_text("qml/qml.qrc")
        self.assertIn("NEXTTASKS_DESKTOP_TEST_AUTH", main)
        self.assertIn("NEXTCLOUD_TEST_SERVER", main)
        self.assertIn("NEXTNEWS_TEST_SERVER", script)
        self.assertIn("/remote.php/dav/calendars/", api)
        self.assertIn("PROPFIND", api)
        self.assertIn("VTODO", api)
        self.assertIn("supported-calendar-component-set", api)
        self.assertIn("function supportsTodo(", api)
        self.assertIn("function loadTasks(", api)
        self.assertIn("signal calendarCreated(int generation)", api)
        self.assertIn("function createCalendar(serverUrl, userName, secret, title)", api)
        self.assertIn("calDavNetwork.createCalendar", api)
        self.assertIn("typeof calDavNetwork", api)
        self.assertNotIn('xhr.open("MKCALENDAR", url)', api)
        self.assertIn("sendCustomRequest", caldav_network)
        self.assertIn("MKCOL", caldav_network)
        self.assertIn("<d:resourcetype><d:collection/><c:calendar/></d:resourcetype>", caldav_network)
        self.assertIn("PROPPATCH", caldav_network)
        self.assertIn("DELETE", caldav_network)
        self.assertIn("MOVE", caldav_network)
        self.assertIn('"Destination"', caldav_network)
        self.assertIn('"Overwrite"', caldav_network)
        self.assertIn('c:comp name=\\"VTODO\\"', caldav_network)
        self.assertIn("calendar-color", caldav_network)
        self.assertIn("calendarCreated", caldav_network)
        self.assertIn("calendarCreateFailed", caldav_network)
        self.assertIn("calendarUpdated", caldav_network)
        self.assertIn("calendarDeleted", caldav_network)
        self.assertIn("void CalDavNetwork::putTask", caldav_network)
        self.assertIn("void CalDavNetwork::deleteTaskObject", caldav_network)
        self.assertIn("void CalDavNetwork::fetchTaskObject", caldav_network)
        self.assertIn("taskPutFinished", caldav_network)
        self.assertIn("taskDeleteFinished", caldav_network)
        self.assertIn("taskFetched", caldav_network)
        self.assertIn("Qt5Network", cmake)
        self.assertIn("Qt5::Network", cmake)
        self.assertIn("CalDavNetwork.cpp", cmake)
        self.assertIn("function updateTaskCompletion(", api)
        self.assertIn('xhr.open("PUT", url)', api)
        self.assertIn('xhr.setRequestHeader("If-Match", task.etag)', api)
        self.assertIn('var etag = decodeName(textOf(block, "getetag"))', api)
        self.assertIn("function updatedCompletionTodo(", api)
        self.assertIn("STATUS:COMPLETED", api)
        self.assertIn("STATUS:NEEDS-ACTION", api)
        self.assertIn("function parseTodo(", api)
        self.assertIn("calendar-data", api)
        self.assertIn('"description": description', api)
        self.assertIn('"etag": etag', api)
        self.assertIn('"href": href', api)
        self.assertIn('"rawTodo": todoText', api)
        controller = read_text("qml/backend/TasksController.qml")
        adapter = read_text("qml/backend/AccountSessionAdapter.qml")
        home = read_text("qml/pages/HomePage.qml")
        account_page = read_text("qml/pages/AccountSelectionPage.qml")
        app_controller = read_text("qml/backend/AppController.qml")
        self.assertIn("signal accountChanged", app_controller)
        self.assertNotIn("signal accountAuthorized", app_controller)
        self.assertNotIn("page.appController.accountAuthorized(", account_page)
        self.assertIn("function onAccountChanged(", home)
        self.assertIn("dataController.applyAccountSelection(accountId, displayName, providerId, serviceId, serverUrl, avatarUrl)", home)
        self.assertNotIn("function onAccountAuthorized(", home)
        self.assertNotIn("dataController.applyAuthorizedAccountSelection(", home)
        self.assertIn("function applyAccountSelection(", controller)
        self.assertNotIn("function applyAuthorizedAccountSelection(", controller)
        self.assertIn("session.setAccount(", controller)
        self.assertNotIn("session.primeCredentials(", controller)
        self.assertIn("function setAccount(", adapter)
        self.assertNotIn("function primeCredentials(", adapter)
        self.assertIn("var accountChanged = currentAccountId !== accountId", adapter)
        self.assertIn("cachedSecret = \"\"", adapter)
        self.assertIn("pendingCallback = null", adapter)
        self.assertIn("accountService.objectHandle = null", adapter)
        self.assertIn("signal authenticated(string userName, string secret, string serverUrl, int accountId, string serviceId)", adapter)
        self.assertIn("function pendingAuthMatchesCurrent()", adapter)
        self.assertIn("authenticateAfterHandleTimer.restart()", adapter)
        self.assertIn("NextTasks Account auth ignored stale response", adapter)
        self.assertIn("selectedServiceAuthenticateTimer.restart()", account_page)
        self.assertIn("function authenticatedUrl(", api)
        self.assertIn('return value.replace("://", "://" + user + "@")', api)
        self.assertIn("function lookupNextcloudUserId(", api)
        self.assertIn("/ocs/v2.php/cloud/user?format=json", api)
        self.assertIn('"OCS-APIRequest"', api)
        self.assertIn('"/remote.php/dav/calendars/" + encodeURIComponent(userId) + "/"', api)
        self.assertIn("NextTasks TasksApi user lookup result", api)
        self.assertIn("url.setUserName(userName)", read_text("CalDavNetwork.cpp"))
        self.assertIn("function handleAccountChanged()", controller)
        self.assertIn("property bool applyingAccountSelection: false", controller)
        self.assertIn("property int accountRequestGeneration: 0", controller)
        refresh_body = controller.split("function refresh()", 1)[1].split("function showMyTasks()", 1)[0]
        self.assertIn("accountRequestGeneration += 1", refresh_body)
        self.assertIn("function stopAccountActivity()", controller)
        self.assertIn("function isCurrentApiGeneration(generation)", controller)
        self.assertIn("ignored stale", controller)
        self.assertIn("if (!controller.applyingAccountSelection) controller.handleAccountChanged()", controller)
        self.assertIn("activeAccountKey = accountKeyFor(accountId, providerId, serviceId, serverUrl)", controller)
        self.assertIn("function accountKeyFor(", controller)
        self.assertIn("function clearAccountData()", controller)
        self.assertIn("function applyLocalTaskIdentity(", controller)
        self.assertIn("function taskByKey(", controller)
        self.assertIn("function openCalendar(", controller)
        self.assertIn("function goBackToMyTasks()", controller)
        self.assertIn("function showMyTasks()", controller)
        self.assertIn("function showCalendarList()", controller)
        self.assertIn("function toggleTaskCompleted(", controller)
        self.assertIn("function reopenCompletedTasksInCurrentScope(", controller)
        self.assertIn("function replaceCalendarTasks(", controller)
        self.assertIn("tasksCache.replaceCalendarTasks(calendarHref, decorated)", controller)
        self.assertIn("function updateTaskCompletionQueue(", controller)
        self.assertIn("function completedTasksForCurrentScope(", controller)
        self.assertIn("function toggleShowCompletedTasks(", controller)
        self.assertIn("property bool showCompletedTasks: false", controller)
        self.assertIn("function sortOptions()", controller)
        self.assertIn("function setSortMode(", controller)
        self.assertIn("function moveManualTask(", controller)
        self.assertIn("function reorderManualTask(", controller)
        self.assertIn("function manualReorderSource(task)", controller)
        self.assertIn("String(candidate.calendarHref || \"\") === calendarHref", controller)
        self.assertIn("property string sortModeByScopeJson", controller)
        self.assertIn('property string sortMode: "due"', controller)
        self.assertIn('"value": "manual"', controller)
        self.assertIn("function currentSortMode()", controller)
        self.assertIn('return "due"', controller)
        self.assertIn("function menuItems()", controller)
        self.assertIn("function activateMenuItem(", controller)
        self.assertIn("completionUpdateRunning", controller)
        self.assertIn("function visibleTasks(", controller)
        visible_tasks_body = controller.split("function visibleTasks(", 1)[1].split("function compareTasks(", 1)[0]
        self.assertNotIn("isHiddenUntilFuture", visible_tasks_body)
        self.assertIn('property string viewMode: "myTasks"', controller)
        self.assertIn('property var calendars: []', controller)
        self.assertIn("function accountKey()", controller)
        self.assertIn('String(serviceId || "") === "desktop-test-env"', controller)
        self.assertIn("onAccountIdChanged: if (!controller.applyingAccountSelection) controller.handleAccountChanged()", controller)
        self.assertIn("property string syncStateText", controller)
        self.assertIn("property string syncStateColor", controller)
        self.assertIn("<file>backend/TasksApiClient.qml</file>", qrc)
        self.assertIn("<file>backend/TasksController.qml</file>", qrc)
        self.assertIn("<file>backend/TasksCache.qml</file>", qrc)
        self.assertIn("property int requestGeneration: 0", api)
        self.assertIn("signal calendarsLoaded(var entries, int generation)", api)
        self.assertIn("<file>pages/TaskDetailPage.qml</file>", qrc)
        self.assertIn("<file>pages/TaskConflictResolutionPage.qml</file>", qrc)
    def test_home_top_bar_contract(self):
        home = read_text("qml/pages/HomePage.qml")
        self.assertIn("contents: RowLayout", home)
        self.assertIn('placeholderText: i18n.tr("Search")', home)
        self.assertNotIn('iconName: "reload"', home)
        self.assertIn("pullRefreshThreshold", home)
        self.assertIn("pullRefreshArmed", home)
        self.assertIn('i18n.tr("Pull to refresh")', home)
        self.assertIn('i18n.tr("Release to refresh")', home)
        self.assertIn("function statusAllowsRefresh()", home)
        self.assertIn('i18n.tr("Refresh")', home)
        self.assertIn("statusDetailsDialog", home)
        self.assertIn("function statusIconKind()", home)
        self.assertIn("function statusAccentColor()", home)
        self.assertIn("function statusDetailsText()", home)
        self.assertIn('i18n.tr("Sync status")', home)
        self.assertIn('readonly property string actionBlue: "#2c7fb8"', home)
        self.assertIn('readonly property string deleteRed: "#c7162b"', home)
        self.assertIn("function openConflictResolution(task)", home)
        self.assertIn("dataController.conflictTasksCount > 0", home)
        self.assertIn("dataController.dirtyTasksCount > 0", home)
        self.assertIn("dataController.loading || dataController.dirtySyncRunning", home)
        self.assertIn("onConflictTasksCountChanged: statusCanvas.requestPaint()", home)
        self.assertIn("onDirtySyncRunningChanged: statusCanvas.requestPaint()", home)
        self.assertIn("onDirtyTasksCountChanged: statusCanvas.requestPaint()", home)
        self.assertIn("function taskFrameColor(entry)", home)
        self.assertIn("function taskFrameWidth(entry)", home)
        self.assertIn("function taskCardColor(entry)", home)
        self.assertIn("function taskStatusBadgeText(entry)", home)
        self.assertIn("function taskStatusBadgeColor(entry)", home)
        self.assertIn("taskStatusBadgeLabel", home)
        self.assertIn("RowLayout", home.split("taskStatusBadgeLabel", 1)[0])
        self.assertIn("page.taskSelected(modelData) ? page.actionBlue : page.taskFrameColor(modelData)", home)
        self.assertIn("color: page.taskCardColor(modelData)", home)
        self.assertIn('i18n.tr("Resolve conflict")', home)
        self.assertIn("TaskConflictResolutionPage.qml", home)
        self.assertIn("OpacityMask", home)
        self.assertIn("accountAvatarSource", home)
        self.assertIn("dataController.openCalendar", home)
        self.assertIn("dataController.goBackToMyTasks", home)
        self.assertIn("dataController.menuItemSelected(modelData)", home)
        self.assertIn("dataController.activateMenuItem(modelData)", home)
        self.assertIn("dataController.menuItems()", home)
        self.assertIn("dataController.menuRevision", home)
        self.assertIn("createListDialog", home)
        self.assertIn("listOptionsDialog", home)
        self.assertIn("deleteListDialog", home)
        self.assertIn("dataController.createCalendar", home)
        self.assertIn("dataController.updateCalendar", home)
        self.assertIn("dataController.deleteCalendar", home)
        self.assertIn("color: page.deleteRed", home)
        self.assertIn("color: page.actionBlue", home)
        self.assertIn('i18n.tr("Create new list")', home)
        self.assertIn('text: "\\u22EE"', home)
        self.assertIn('i18n.tr("The list and its tasks will be removed from the server and this device.")', home)
        self.assertIn("dataController.activateMenuItem(modelData)", home)
        self.assertIn("dataController.toggleTaskCompleted(modelData)", home)
        self.assertIn("function requestDeleteTask(task)", home)
        self.assertIn("deleteTaskDialog", home)
        self.assertIn("drag.target: page.selectionMode ? null", home)
        self.assertIn("drag.axis: Drag.XAxis", home)
        self.assertIn("if (offset > 0)", home)
        self.assertIn("page.requestDeleteTask(modelData)", home)
        self.assertIn("else if (offset < 0", home)
        self.assertIn("dataController.toggleTaskCompleted(modelData)", home)
        self.assertIn("i18n.tr(\"Complete\")", home)
        self.assertIn("units.gu(8.8)", home)
        self.assertNotIn('i18n.tr("Done")', home)
        self.assertIn("dataController.toggleShowCompletedTasks()", home)
        self.assertIn("dataController.reopenCompletedTasksInCurrentScope()", home)
        self.assertIn("function sectionedEntries(", home)
        self.assertIn('i18n.tr("Task Lists")', home)
        self.assertIn('i18n.tr("Show completed tasks (%1)")', home)
        self.assertIn('i18n.tr("Reopen all")', home)
        self.assertIn('visible: dataController.viewMode === "calendarTasks" && dataController.showCompletedTasks', home)
        self.assertIn('i18n.tr("This will mark all completed tasks in this list as open again.")', home)
        self.assertIn("sortDialog", home)
        self.assertIn("dataController.sortOptions()", home)
        self.assertIn("PopupUtils.open(sortDialog)", home)
        self.assertIn("dataController.reorderManualTask(modelData", home)
        self.assertIn("page.manualDragTaskKey", home)
        self.assertIn("page.manualDropBeforeTaskKey", home)
        self.assertIn("page.updateManualDropTarget(modelData", home)
        self.assertNotIn("NextTasks ManualDrag", home)
        self.assertIn("function beginManualDrag(", home)
        self.assertIn("function updateManualDrag(", home)
        self.assertIn("function finishManualDrag(", home)
        self.assertIn("id: dragHandleArea", home)
        self.assertIn("dragHandleArea.mapToItem(page, mouse.x, mouse.y).y", home)
        self.assertIn('text: "\\u2630"', home)
        self.assertIn("dataController.pauseUserSync()", home)
        self.assertIn("dataController.resumeUserSync()", home)
        self.assertIn("property var selectedTaskKeys", home)
        self.assertIn("property bool selectionMode", home)
        self.assertIn("function selectedTaskCount()", home)
        self.assertIn("function clearSelection()", home)
        self.assertIn("function toggleTaskSelection(task)", home)
        self.assertIn("bulkDeleteConfirmDialog", home)
        self.assertIn('i18n.tr("Delete selected tasks?")', home)
        self.assertIn("dataController.deleteTasksByKeys(page.selectedTaskKeys)", home)
        self.assertIn("page.selectionMode ? \"\\u2715\" : \"\\u2630\"", home)
        self.assertIn("page.selectionMode && modelData.type === \"task\"", home)
        self.assertIn("taskRow.manualDragActive", home)
        self.assertIn("property bool manualDragCapture", home)
        self.assertIn("property bool manualDragPointerCaptured", home)
        self.assertNotIn("pressAndHoldInterval", home)
        self.assertIn("manualDragCapture = true", home)
        self.assertIn("onPositionChanged", home)
        self.assertIn("taskRow.manualDragMoved", home)
        self.assertIn("interactive: page.manualDragTaskKey.length === 0", home)
        self.assertNotIn("liveDirection", home)
        self.assertNotIn("dataController.moveManualTask(modelData, liveDirection)", home)
        self.assertIn('i18n.tr("Manual order is saved to the task list using Nextcloud-compatible task order values.")', home)
        self.assertNotIn("dataController.moveManualTask(modelData, -1)", home)
        self.assertIn('radius: units.gu(0.35)', home)
        self.assertNotIn('\\u25cb', home)
        controller = read_text("qml/backend/TasksController.qml")
        self.assertIn('i18n.tr("My Tasks")', controller)
        self.assertIn('i18n.tr("Lists")', controller)
        self.assertIn("property bool userSyncPaused", controller)
        self.assertIn("function pauseUserSync()", controller)
        self.assertIn("function resumeUserSync()", controller)
        self.assertIn("function openTask(", home)
        self.assertIn("TaskDetailPage.qml", home)
    def test_task_detail_contract(self):
        detail = read_text("qml/pages/TaskDetailPage.qml")
        self.assertIn('property string activeTab: "details"', detail)
        self.assertIn("property string titleText", detail)
        self.assertIn("property string statusValue", detail)
        self.assertIn("property string percentText", detail)
        self.assertIn("property string locationText", detail)
        self.assertIn("property string urlText", detail)
        self.assertIn("property string tagsText", detail)
        self.assertIn('readonly property string actionBlue: "#2c7fb8"', detail)
        self.assertIn('readonly property string deleteRed: "#c7162b"', detail)
        self.assertIn("TextField", detail)
        self.assertIn("id: autoSaveTimer", detail)
        self.assertIn("id: syncStatusDialog", detail)
        self.assertIn("function statusIconKind()", detail)
        self.assertIn("function statusAccentColor()", detail)
        self.assertIn("function openStatusFromIcon()", detail)
        self.assertIn("function refreshTaskFromController()", detail)
        self.assertIn("function currentFieldsMatchTask(candidate)", detail)
        self.assertIn("if (!dirty || currentFieldsMatchTask(updatedTask))", detail)
        self.assertIn("tasksController.taskByKey(task)", detail)
        self.assertIn("function scheduleAutoSave()", detail)
        self.assertIn("function performAutoSave()", detail)
        self.assertIn("property bool inputEditing: false", detail)
        self.assertIn("if (page.inputEditing || dirty || autoSaveTimer.running || deferredSaveTimer.running)", detail)
        self.assertIn("onActiveFocusChanged", detail)
        self.assertIn("function updateInputEditingState()", detail)
        self.assertIn("result.localModified = Date.now()", detail)
        self.assertIn("tasksController.saveTask(task, changes)", detail)
        self.assertIn("tasksController.updateTaskLocalDraft(task, currentChanges())", detail)
        self.assertNotIn("if (!tasksController || tasksController.loading || !dirty)", detail)
        self.assertIn('i18n.tr("Details")', detail)
        self.assertIn('i18n.tr("Status")', detail)
        self.assertIn('i18n.tr("Needs action")', detail)
        self.assertIn('i18n.tr("Start date")', detail)
        self.assertIn('i18n.tr("Due date")', detail)
        self.assertIn('i18n.tr("Priority")', detail)
        self.assertIn('id: datePickerDialog', detail)
        self.assertIn("calendarCellDate", detail)
        self.assertIn("calendarCellToday", detail)
        self.assertIn("shiftCalendarMonth", detail)
        self.assertIn('id: statusDialog', detail)
        self.assertIn('id: tagsDialog', detail)
        self.assertIn('id: prioritySlider', detail)
        self.assertIn('id: percentSlider', detail)
        self.assertIn('function openDateDialog(', detail)
        self.assertIn('function applyDateDialogValue(', detail)
        self.assertIn('function priorityLabel()', detail)
        self.assertIn('function setPriorityFromX(', detail)
        self.assertIn('function setPercentFromX(', detail)
        self.assertIn('function addTag(', detail)
        self.assertIn('function toggleTag(', detail)
        self.assertIn('function availableTags()', detail)
        self.assertIn('function tagSelected(', detail)
        self.assertIn('i18n.tr("Today")', detail)
        self.assertIn('i18n.tr("In progress")', detail)
        self.assertIn('i18n.tr("Canceled")', detail)
        self.assertIn('i18n.tr("No priority assigned (0)")', detail)
        self.assertIn('i18n.tr("High (%1)")', detail)
        self.assertIn('i18n.tr("Medium (5)")', detail)
        self.assertIn('i18n.tr("Low (%1)")', detail)
        self.assertIn('i18n.tr("Set location")', detail)
        self.assertIn('i18n.tr("Set a URL")', detail)
        self.assertIn('i18n.tr("Select tags")', detail)
        self.assertIn('i18n.tr("New tag")', detail)
        self.assertIn('i18n.tr("Selected: %1")', detail)
        self.assertIn('i18n.tr("Done")', detail)
        self.assertIn('i18n.tr("List: %1")', detail)
        self.assertIn('i18n.tr("Notes")', detail)
        self.assertIn("PopupUtils.open(statusDialog)", detail)
        self.assertIn('text: "\\u2611"', detail)
        self.assertIn("readOnly: false", detail)
        self.assertNotIn('i18n.tr("Save changes")', detail)
    def test_task_update_contract(self):
        api = read_text("qml/backend/TasksApiClient.qml")
        controller = read_text("qml/backend/TasksController.qml")
        self.assertIn("function updateTask(", api)
        self.assertIn("function updatedTaskTodo(", api)
        self.assertIn("function syncableLocalChanges(tasks)", controller)
        self.assertIn('i18n.tr("New task waiting for a title before sync.")', controller)
        self.assertIn("result.localModified = Date.now()", controller)
        self.assertIn('xhr.open("PUT"', api)
        self.assertIn('"If-Match"', api)
        self.assertIn('"SUMMARY:"', api)
        self.assertIn('"DESCRIPTION:"', api)
        self.assertIn('"DTSTART;VALUE=DATE:"', api)
        self.assertIn('"DUE;VALUE=DATE:"', api)
        self.assertIn('"PRIORITY:"', api)
        self.assertIn('"PERCENT-COMPLETE:"', api)
        self.assertIn("X-APPLE-SORT-ORDER", api)
        self.assertIn('lines = removeProperty(lines, "X-APPLE-SORT-ORDER")', api)
        self.assertIn("normalizeSortOrder", api)
        self.assertIn('"LOCATION:"', api)
        self.assertIn('"URL:"', api)
        self.assertIn('"CATEGORIES:"', api)
        self.assertIn("function escapeCategories(", api)
        self.assertIn("signal taskUpdated", api)
        self.assertIn('getResponseHeader("ETag")', api)
        self.assertIn("function saveTask(", controller)
        self.assertIn("function updateTaskLocalDraft(", controller)
        self.assertIn("function mergeTaskChanges(", controller)
        self.assertIn("function startTaskUpdate()", controller)
        self.assertIn("onTaskUpdated", controller)
    def test_task_cache_and_dirty_sync_contract(self):
        cache = read_text("qml/backend/TasksCache.qml")
        controller = read_text("qml/backend/TasksController.qml")
        self.assertIn("import QtQuick.LocalStorage 2.0 as Sql", cache)
        self.assertIn('readonly property string statusEdited: "LOCAL_EDITED"', cache)
        self.assertIn('readonly property string statusCreated: "LOCAL_CREATED"', cache)
        self.assertIn('readonly property string statusDeleted: "LOCAL_DELETED"', cache)
        self.assertIn("Sql.LocalStorage.openDatabaseSync(databaseName", cache)
        self.assertIn("CREATE TABLE IF NOT EXISTS calendars", cache)
        self.assertIn("CREATE TABLE IF NOT EXISTS tasks", cache)
        for column in ["raw_todo", "etag", "local_status", "local_modified", "conflict", "calendar_href", "percent_complete", "CATEGORIES"]:
            if column == "CATEGORIES":
                self.assertIn('"tags"', cache)
            else:
                self.assertIn(column, cache)
        self.assertIn("function setScope(scopeKey)", cache)
        self.assertIn("function loadLocalChanges()", cache)
        self.assertIn("color TEXT DEFAULT ''", cache)
        self.assertIn("sort_order INTEGER DEFAULT 0", cache)
        self.assertIn('"sortOrder": Number(row.sort_order || 0)', cache)
        self.assertIn("CREATE TABLE IF NOT EXISTS deleted_calendars", cache)
        self.assertIn("function canonicalCalendarHref(value)", cache)
        self.assertIn("SELECT href FROM deleted_calendars WHERE href = ?", cache)
        self.assertIn("INSERT OR REPLACE INTO deleted_calendars", cache)
        self.assertIn("replaceCalendars skipped tombstoned calendar", cache)
        self.assertIn("function clearCleanServerDataForCurrentScope()", cache)
        clear_body = cache.split("function clearCleanServerDataForCurrentScope()", 1)[1].split("function loadTasksForCalendar", 1)[0]
        self.assertNotIn("DELETE FROM deleted_calendars", clear_body)
        self.assertIn("function deleteCalendar(calendarHref)", cache)
        self.assertIn("function deleteTasksForCalendarHref(tx, calendarHref, cleanOnly)", cache)
        self.assertIn("function purgeDeletedCalendarTasks(tx)", cache)
        self.assertIn("canonicalCalendarHref(row.calendar_href || \"\")", cache)
        self.assertIn("DELETE FROM tasks WHERE task_key = ?", cache)
        self.assertIn("local_status IN (?, ?, ?)", cache)
        self.assertIn("[statusCreated, statusEdited, statusDeleted]", cache)
        self.assertIn("function hasMeaningfulContent(task)", cache)
        self.assertIn("task.localStatus === statusCreated && !hasMeaningfulContent(task)", cache)
        self.assertIn("conflict = 0", cache)
        self.assertIn("function saveLocalDraft(task)", cache)
        self.assertIn("function sameMeaningfulTaskFields(row, task)", cache)
        self.assertIn("existingLocalModified > uploadedLocalModified && !sameMeaningfulTaskFields(existing, task)", cache)
        self.assertIn("existingStatus === statusCreated", cache)
        self.assertIn("saveUploadedTask converted newer created draft to edited", cache)
        self.assertIn("SELECT task_key, local_status", cache)
        self.assertIn("WHERE uid = ?", cache)
        self.assertIn("oldKey.length > 0 && oldKey !== key", cache)
        self.assertIn("function createLocalTask(", cache)
        self.assertIn("function markDeleted(task)", cache)
        self.assertIn("function deleteTask(task)", cache)
        self.assertIn('"isNew": localStatus === statusCreated', cache)
        self.assertIn('"deleted": localStatus === statusDeleted', cache)
        self.assertIn("function replaceCalendarTasks(calendarHref, tasks)", cache)
        self.assertIn("function markConflict(task, serverTask)", cache)
        self.assertIn("TasksCache {", controller)
        self.assertIn("function loadCachedState()", controller)
        self.assertIn("loadCachedState()", controller.split("function refresh()", 1)[1].split("function showMyTasks()", 1)[0])
        self.assertIn("tasksCache.loadLocalChanges()", controller)
        self.assertIn("dirtySyncRunning", controller)
        self.assertIn("property bool dirtySyncQueuedAfterLoading: false", controller)
        self.assertIn("property int dirtyTasksCount: 0", controller)
        self.assertIn("property int accountDataRevision: 0", controller)
        self.assertIn("accountDataRevision += 1", controller)
        self.assertIn("id: autoDirtySyncTimer", controller)
        self.assertIn("interval: 500", controller)
        self.assertIn("function scheduleDirtyAutoSync()", controller)
        self.assertIn("function autoDirtySyncNow()", controller)
        self.assertIn("function updateDirtySummary()", controller)
        self.assertIn("function markUpToDateIfClean()", controller)
        self.assertIn("remainingLocalChanges.length > 0", controller)
        self.assertIn("updateDirtySummary()", controller.split("function scheduleDirtyAutoSync()", 1)[1].split("function autoDirtySyncNow()", 1)[0])
        self.assertIn("scheduleDirtyAutoSync()", controller)
        self.assertIn("autoDirtySyncTimer.stop()", controller)
        self.assertIn("function startDirtySync(", controller)
        self.assertIn("function runQueuedDirtySyncIfReady()", controller)
        self.assertIn("function startNextDirtySync()", controller)
        self.assertIn("function finishDirtySync()", controller)
        self.assertIn("function createTask()", controller)
        self.assertIn("function deleteTask(task)", controller)
        self.assertIn("function deleteTasksByKeys(taskKeys)", controller)
        self.assertIn("function availableMoveCalendars(task)", controller)
        self.assertIn("function availableMoveCalendarsForTasks(tasks)", controller)
        self.assertIn("function calendarHrefForTask(task)", controller)
        self.assertIn("function normalizedCalendarHref(value)", controller)
        self.assertIn("function sameCalendarHref(left, right)", controller)
        self.assertIn("function normalizedCalendarTitle(value)", controller)
        self.assertIn("function sameCalendarTitle(left, right)", controller)
        self.assertIn("var href = normalizedCalendarHref(calendarHrefForTask(selected[i]))", controller)
        self.assertIn("selectedCalendarHrefs[href] = true", controller)
        self.assertIn("selectedCalendarTitles[title] = true", controller)
        self.assertIn("var same = selectedCalendarHrefs[normalizedHref] === true", controller)
        self.assertIn("selectedCalendarTitles[normalizedTitle] === true", controller)
        self.assertIn("if (same) continue", controller)
        self.assertIn("function moveTaskToCalendar(task, targetCalendar)", controller)
        self.assertIn("function moveTasksByKeysToCalendar(taskKeys, targetCalendar)", controller)
        self.assertIn("function canMoveTasksToCalendar(tasks, targetCalendar)", controller)
        self.assertIn("function startNextTaskMove()", controller)
        self.assertIn("function refreshMenuCounts()", controller)
        self.assertIn("property string pendingOpenCalendarTitle", controller)
        self.assertIn("function findCalendarByTitle(title)", controller)
        self.assertIn("controller.pendingOpenCalendarTitle = createdTitle", controller)
        self.assertIn("api.createTask(currentServerUrl, currentUserName, currentSecret, pendingUpdateTask, pendingUpdateChanges)", controller)
        self.assertIn("api.deleteTask(currentServerUrl, currentUserName, currentSecret, pendingUpdateTask)", controller)
        self.assertIn("var wasNew = source.isNew === true || source.localStatus === tasksCache.statusCreated", controller)
        self.assertIn("result.localStatus = wasNew ? tasksCache.statusCreated : tasksCache.statusEdited", controller)
        self.assertIn("result.dirty = true", controller)
        self.assertIn("result.isNew = wasNew", controller)
        self.assertIn("function handleDirtyWriteFailure(", controller)
        self.assertIn("function isConflictMessage(", controller)
        self.assertIn("function removeTask(task)", controller)
        self.assertIn("tasksCache.saveLocalDraft(localTask)", controller)
        self.assertIn("mergeTaskChanges(taskByKey(task) || task, changes || {})", controller)
        self.assertIn("tasksCache.saveUploadedTask(updatedTask)", controller)
        self.assertIn("tasksCache.replaceCalendars(entries)", controller)
        self.assertIn("controller.calendars = tasksCache.loadCalendars()", controller)
        self.assertIn("controller.loadMyTasksFromCalendars(controller.calendars)", controller)
        self.assertIn("tasksCache.replaceCalendarTasks(calendarHref, decorated)", controller)
        self.assertIn("allTasks = []", controller.split("function loadMyTasksFromCalendars", 1)[1].split("function loadNextPendingCalendar", 1)[0])
        self.assertIn("entries = []", controller.split("function loadMyTasksFromCalendars", 1)[1].split("function loadNextPendingCalendar", 1)[0])
        self.assertIn("function tasksForKnownCalendars(tasks, sourceCalendars)", controller)
        self.assertIn("allTasks = tasksForKnownCalendars(tasksCache.loadAllTasks(), calendars)", controller)
        self.assertIn("startDirtySync(false)", controller)
        self.assertNotIn("startDirtySync(true)", controller.split("function scheduleDirtyAutoSync", 1)[1].split("function menuItems", 1)[0])
    def test_task_create_delete_contract(self):
        api = read_text("qml/backend/TasksApiClient.qml")
        controller = read_text("qml/backend/TasksController.qml")
        cache = read_text("qml/backend/TasksCache.qml")
        home = read_text("qml/pages/HomePage.qml")
        detail = read_text("qml/pages/TaskDetailPage.qml")
        self.assertIn("signal taskCreated(var task, int generation)", api)
        self.assertIn("signal taskDeleted(var task, int generation)", api)
        self.assertIn("signal taskMoved(var sourceTask, var movedTask, int generation)", api)
        self.assertIn("function createTask(serverUrl, userName, secret, task, changes)", api)
        self.assertIn("function deleteTask(serverUrl, userName, secret, task)", api)
        self.assertIn("function moveTask(serverUrl, userName, secret, task, targetCalendar)", api)
        self.assertIn("calDavNetwork.putTask", api)
        self.assertIn("calDavNetwork.deleteTaskObject", api)
        self.assertIn("calDavNetwork.fetchTaskObject", api)
        self.assertIn("function handleNativeTaskPutFinished(", api)
        self.assertIn("function handleNativeTaskDeleteFinished(", api)
        self.assertIn("function handleNativeTaskFetched(", api)
        self.assertIn("function nativeFetchKey(kind, generation)", api)
        self.assertIn("pendingNativeFetches[nativeFetchKey(", api)
        self.assertIn("function discoverCalendarHome(", api)
        self.assertIn("current-user-principal", api)
        self.assertIn("calendar-home-set", api)
        self.assertIn("function fetchWrittenTask(", api)
        self.assertIn("function emitWrittenTaskFallback(", api)
        self.assertIn("calDavNetwork.moveTask", api)
        self.assertIn("function destinationTaskHref(", api)
        self.assertIn('xhr.setRequestHeader("If-None-Match", "*")', api)
        self.assertIn('xhr.open("DELETE", url)', api)
        self.assertIn("xhr.status === 404 || xhr.status === 410", api)
        self.assertIn("function setSortModeForCalendar(calendarHref, mode)", controller)
        self.assertIn("function sortedTasksForCalendar(tasks, calendarHref)", controller)
        self.assertIn("function sortModeForCalendar(calendarHref)", controller)
        self.assertIn("function visibleSortCalendars()", controller)
        self.assertIn("sortScopeForCalendar(href)", controller)
        self.assertIn("function tasksForCurrentScope()", controller)
        self.assertNotIn("return scoped.length > 0 ? scoped : entries", controller)
        self.assertIn("dataController.sortedTasksForCalendar(group, href)", home)
        self.assertIn("id: sortScopeDialog", home)
        self.assertIn("function openSortPicker()", home)
        self.assertIn("BEGIN:VTODO", cache)
        self.assertIn('uid + ".ics"', cache)
        self.assertIn('"title": ""', cache)
        self.assertIn('task.title || ""', cache)
        self.assertIn('"title": row.title || ""', cache)
        self.assertIn("return String(task.href || task.uid || task.title || \"\")", cache)
        self.assertIn("preserved newer local draft with refreshed etag", cache)
        self.assertIn("return String(task.href || task.uid || task.title || \"\")", controller)
        self.assertIn("task.href || task.uid || task.title", home)
        self.assertNotIn('"SUMMARY:" + escapeIcs(i18n.tr("Untitled task"))', cache)
        self.assertIn("onTaskCreated", controller)
        self.assertIn("onTaskDeleted", controller)
        self.assertIn("onTaskMoved", controller)
        self.assertIn("onTaskMoveFailed", controller)
        self.assertIn("function createTargetCalendar()", controller)
        self.assertIn("function createTaskInCalendar(", controller)
        self.assertIn("function availableCreateCalendars()", controller)
        self.assertIn('i18n.tr("No task list is available for new tasks.")', controller)
        self.assertIn("tasksCache.createLocalTask(targetCalendar.href, targetCalendar.title)", controller)
        self.assertIn("tasksCache.markDeleted(task)", controller)
        self.assertIn("dataController.createTask()", home)
        self.assertIn("dataController.createTaskInCalendar(calendar)", home)
        self.assertIn("dataController.moveTasksByKeysToCalendar(page.selectedTaskKeys, modelData)", home)
        self.assertIn("onAccountDataRevisionChanged", home)
        self.assertIn("page.filteredEntries = []", home)
        self.assertIn("page.displayEntries = []", home)
        self.assertIn("property var bulkMoveTasks: []", home)
        self.assertIn("property var bulkMoveCalendars: []", home)
        self.assertIn("property var createTaskCalendars: []", home)
        self.assertIn("bulkMoveTasks = selectedTasks()", home)
        self.assertIn("bulkMoveCalendars = dataController.availableMoveCalendarsForTasks(bulkMoveTasks)", home)
        self.assertIn("page.createTaskCalendars = calendars", home)
        self.assertIn("model: page.createTaskCalendars", home)
        self.assertIn("visible: dataController.canMoveTasksToCalendar(page.bulkMoveTasks, modelData)", home)
        self.assertIn("bulkMoveDialog", home)
        self.assertIn("createTaskListDialog", home)
        self.assertIn('i18n.tr("Choose task list")', home)
        self.assertIn("dataController.availableCreateCalendars()", home)
        self.assertIn("function createTask()", home)
        self.assertIn('visible: !page.drawerOpen && !page.selectionMode && dataController.viewMode !== "calendarList"', home)
        self.assertIn('i18n.tr("New")', home)
        self.assertIn('i18n.tr("Delete pending")', home)
        self.assertIn("deleteTaskDialog", detail)
        self.assertIn("moveTaskDialog", detail)
        self.assertIn("tasksController.moveTaskToCalendar(task, targetCalendar)", detail)
        self.assertIn("tasksController.deleteTask(task)", detail)
        self.assertIn('placeholderText: i18n.tr("Task title")', detail)
        self.assertIn("function editorTitle(source)", detail)
        self.assertIn("titleText = editorTitle(task)", detail)
        self.assertIn('"title": titleText', detail)
        self.assertNotIn('i18n.tr("New task waiting to sync.")', detail)
        self.assertNotIn('i18n.tr("Local changes waiting to sync.")', detail)
    def test_task_conflict_resolution_contract(self):
        api = read_text("qml/backend/TasksApiClient.qml")
        cache = read_text("qml/backend/TasksCache.qml")
        controller = read_text("qml/backend/TasksController.qml")
        conflict_page = read_text("qml/pages/TaskConflictResolutionPage.qml")
        detail = read_text("qml/pages/TaskDetailPage.qml")
        self.assertIn("signal taskConflict(var localTask, var serverTask, string message, int generation)", api)
        self.assertIn("function fetchConflictTask(", api)
        self.assertIn("PROPFIND", api)
        self.assertIn('xhr.setRequestHeader("Depth", "0")', api)
        self.assertIn("fetchConflictTask(serverUrl, userName, secret, task", api)
        self.assertIn("conflict_etag", cache)
        self.assertIn("function keepLocalTaskAfterConflict(task)", cache)
        self.assertIn("function discardLocalTaskAndUseServer(task, serverTask)", cache)
        self.assertIn("markConflict(task, serverTask)", cache)
        self.assertIn("property int conflictTasksCount", controller)
        self.assertIn("onTaskConflict", controller)
        self.assertIn("function keepLocalTaskAfterConflict(task)", controller)
        self.assertIn("function discardLocalTaskAndUseServer(task)", controller)
        self.assertIn("function serverConflictTask(task)", controller)
        self.assertIn("function conflictPreviewText(task, version)", controller)
        self.assertIn("function firstConflictTask()", controller)
        self.assertIn("function updateConflictSummary()", controller)
        self.assertIn("TaskConflictResolutionPage.qml", detail)
        for snippet in [
            'i18n.tr("Server version")',
            'i18n.tr("Local version")',
            'i18n.tr("Use server version")',
            'i18n.tr("Keep local version")',
            "tasksController.discardLocalTaskAndUseServer(task)",
            "tasksController.keepLocalTaskAfterConflict(task)",
            "tasksController.conflictPreviewText(task, page.selectedVersion)",
        ]:
            self.assertIn(snippet, conflict_page)
if __name__ == "__main__": unittest.main()
